### ISSUE TITLE
bin_runner problems in boson 1.2.4

### ISSUE THREAD

**Issue by zhando** [cldwalker/boson#43]
I'm transitioning to boson > 1.0 too.. I did this all the time with the old boson:

``` ruby
module MyLib                                                                                                                   
  #@options :param1=>{:type=>:numeric}, :verbose=>:boolean                                                                     
  #This is what it does, blah, blah.                                                                                           
  def my_cmd(options={})                                                                                                       
    puts "param1: #{options[:param1]}"                                                                                         
    puts "yeah!" if options[:verbose]                                                                                          
  end                                                                                                                          

  def another_cmd(options={})                                                                                                  
    str = ' -p 1 -v'                                                                                                           
    my_cmd str                                                                                                                 
  end                                                                                                                          
end 
```

so.. (oldboson is simply bin/boson with a gem 'boson', '~> 0.4' directive)

> $ oldboson -d -b -l mylib another_cmd
> param1: 1
> yeah!

but with boson 1.2.4 

> $ boson -d -b -l mylib another_cmd  
> 'another_cmd' was called incorrectly.
> Usage: another_cmd [options={}]
> Original error: wrong number of arguments (2 for 1)
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/lib/boson/option_command.rb:93:in `check_argument_size'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/lib/boson/scientist.rb:136:in`translate_args'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/lib/boson/scientist.rb:105:in `analyze'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/more_scientist.rb:40:in`analyze'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/lib/boson/scientist.rb:86:in `block in redefine_command_block'
>   /home/summa/.boson/commands/mylib.rb:11:in`another_cmd'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/namespacer.rb:16:in `full_invoke'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/lib/boson/bare_runner.rb:42:in`execute_command'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/save.rb:174:in `execute_command'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/pipe_runner.rb:24:in`block in execute_command'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/pipe_runner.rb:22:in `each'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/pipe_runner.rb:22:in`inject'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/pipe_runner.rb:22:in `execute_command'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/science.rb:244:in`execute_command'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/lib/boson/bin_runner.rb:25:in `execute_option_or_command'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-more-0.2.2/lib/boson/runner_options.rb:67:in`execute_option_or_command'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/lib/boson/bin_runner.rb:102:in `start'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/gems/boson-1.2.4/bin/boson:6:in`<top (required)>'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/bin/boson:19:in `load'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/bin/boson:19:in`<main>'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
>   /home/summa/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in`<main>'

However it works just fine with console_runner

> $ boson -d -b -l mylib -c
> irb(main):001:0> another_cmd
> param1: 1
> yeah!
> => nil
> irb(main):002:0>

or

> $ ripl
> Firing up Ripltools
> Firing up Irbtools...
> Welcome to RIPL. You are using ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]. Have fun ;)
> The following commands conflict with existing commands: install. Attempting load into the namespace web_core...
> The following commands conflict with existing commands: menu. Attempting load into the namespace view_core...
> 
> > load_library 'mylib'
> > Loaded library mylib
> > => true
> > another_cmd
> > param1: 1
> > yeah!
> > => nil

**Comment by zhando** [comment]
Ok upon further examination it looks like this problem started with boson v1.1.1

**Comment by zhando** [comment]
Ok, this:

``` Ruby
module MyLib                                                                                                                   
  #@options :param1=>{:type=>:numeric}, :verbose=>:boolean                                                                     
  #This is what it does, blah, blah.                                                                                           
  def my_cmd(options={})                                                                                                       
    puts "param1: #{options[:param1]}"                                                                                         
    puts "yeah!" if options[:verbose]                                                                                          
  end                                                                                                                          

  def another_cmd(options={})                                                                                                  
    str = ' -p 1 -v'                                                                                                           
    Boson.full_invoke('my_cmd', str.split(' '))                                                                                                                 
  end                                                                                                                          
end 
```

makes the bin runner problem go away, but then it doesn't work at the console

**Comment by zhando** [comment]
Ok I can work around all the problems with Boson.in_shell..

But it makes me a bit nostalgic for the days boson 1.1.0 and earlier..

**Comment by zhando** [comment]
I guess I CAN work around the problems.. but if only strange little corner and edge cases didn't keep popping up..

running commands from my file libraries at the console gives me the least headache. Rather not do that though.

btw, just dumped thor out of one of my apps. Hacked up my first runner.rb.. That's working pretty slick.

**Comment by zhando** [comment]
Ok I'm closing this because I think I see the right way forward now.
