### ISSUE TITLE
LoadError: cannot load such file -- alias

### ISSUE THREAD

**Issue by mattscilipoti** [cldwalker/boson#48]
I just followed the installation instructions and I am receiving an error when I run `boson libraries`.

```
Error while loading ~/.bosonrc:
LoadError: cannot load such file -- alias
    /Users/matt/.rvm/rubies/ruby-1.9.3-p385-rails/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /Users/matt/.rvm/rubies/ruby-1.9.3-p385-rails/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-more-0.2.2/lib/boson/alias.rb:1:in `<top (required)>'
    /Users/matt/.rvm/rubies/ruby-1.9.3-p385-rails/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /Users/matt/.rvm/rubies/ruby-1.9.3-p385-rails/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-more-0.2.2/lib/boson/more.rb:1:in `<top (required)>'
    /Users/matt/.rvm/rubies/ruby-1.9.3-p385-rails/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    /Users/matt/.rvm/rubies/ruby-1.9.3-p385-rails/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    /Users/matt/.rvm/rubies/ruby-1.9.3-p385-rails/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    /Users/matt/.bosonrc:1:in `<top (required)>'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-1.2.4/lib/boson/bare_runner.rb:78:in `load'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-1.2.4/lib/boson/bare_runner.rb:78:in `load_rc'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-1.2.4/lib/boson/bare_runner.rb:14:in `start'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-1.2.4/lib/boson/bin_runner.rb:92:in `start'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-1.2.4/bin/boson:6:in `<top (required)>'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/bin/boson:19:in `load'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/bin/boson:19:in `<main>'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/bin/ruby_noexec_wrapper:14:in `eval'
    /Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/bin/ruby_noexec_wrapper:14:in `<main>'
Could not find command "libraries"
```

Workaround: manually install alias gem.

I see `/Users/matt/.rvm/gems/ruby-1.9.3-p385-rails/gems/boson-more-0.2.2/bundle/ruby/1.9.1/gems/alias-0.2.3`, but I could not find where this path should be included.  Should this be added to gemspec? 
- ruby-1.9.3-p385
- boson (1.2.4)
- boson-more (0.2.2)

**Comment by cldwalker** [comment]
Hey. Sorry for the delay. boson-more is a collection of useful plugins, some of which require additional dependencies. I've mentioned in the readme, you need to add the alias gem, https://github.com/cldwalker/boson-more#list-of-plugins . Make sense?

**Comment by cldwalker** [comment]
Closing. Ping me if there's more to this
