### ISSUE TITLE
LoadError: cannot load such file -- alias on Ruby 2.1.2

### ISSUE THREAD

**Issue by martinos** [cldwalker/boson#53]
When I launch boson command I get the following error:

``` bash
~$ boson commands
Error while loading ~/.bosonrc:
LoadError: cannot load such file -- alias
    /Users/coco/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /Users/coco/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /Users/coco/.gem/ruby/2.1.2/gems/boson-more-0.3.0/lib/boson/alias.rb:1:in `<top (required)>'
    /Users/coco/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /Users/coco/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /Users/coco/.gem/ruby/2.1.2/gems/boson-more-0.3.0/lib/boson/more.rb:1:in `<top (required)>'
    /Users/coco/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    /Users/coco/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    /Users/mchabot/.rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    /Users/mchabot/.bosonrc:1:in `<top (required)>'
    /Users/mchabot/.gem/ruby/2.1.2/gems/boson-1.3.0/lib/boson/bare_runner.rb:78:in `load'
    /Users/mchabot/.gem/ruby/2.1.2/gems/boson-1.3.0/lib/boson/bare_runner.rb:78:in `load_rc'
    /Users/mchabot/.gem/ruby/2.1.2/gems/boson-1.3.0/lib/boson/bare_runner.rb:14:in `start'
    /Users/mchabot/.gem/ruby/2.1.2/gems/boson-1.3.0/lib/boson/bin_runner.rb:92:in `start'
    /Users/mchabot/.gem/ruby/2.1.2/gems/boson-1.3.0/bin/boson:6:in `<top (required)>'
    /Users/mchabot/.gem/ruby/2.1.2/bin/boson:23:in `load'
    /Users/mchabot/.gem/ruby/2.1.2/bin/boson:23:in `<main>'
Could not find command "commands"
```

Here is the content of my .bosonrc:

``` bash
~$ cat .bosonrc
require 'boson/more'
```

And my installed gems:

``` ruby
~$ gem list 

*** LOCAL GEMS ***

bigdecimal (1.2.4)
boson (1.3.0)
boson-more (0.3.0)
erubis (2.7.0)
gist (4.2.1)
haml (4.0.5)
hpricot (0.8.6)
html2haml (1.0.1)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
ruby_parser (3.1.3)
sexp_processor (4.4.3)
test-unit (2.1.2.0)
tilt (2.0.1)
```

My ruby version

``` bash
~$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

My gem environment:

``` bash
~$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.2 (2014-05-08 patchlevel 95) [x86_64-darwin13.0]
  - INSTALLATION DIRECTORY: /Users/mchabot/.gem/ruby/2.1.2
  - RUBY EXECUTABLE: /Users/mchabot/.rubies/ruby-2.1.2/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/mchabot/.gem/ruby/2.1.2/bin
  - SPEC CACHE DIRECTORY: /Users/mchabot/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/mchabot/.gem/ruby/2.1.2
     - /Users/mchabot/.rubies/ruby-2.1.2/lib/ruby/gems/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/mchabot/.gem/ruby/2.1.2/bin
     - /Users/mchabot/.rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/bin
     - /Users/mchabot/.rubies/ruby-2.1.2/bin
     - ./bin
     - /Users/mchabot/go/bin
     - /Users/mchabot/bin/shared
     - /usr/local/heroku/bin
     - /Users/mchabot/go/bin
     - /Users/mchabot/bin/
     - /usr/local/share/python
     - /usr/local//bin/
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/local/git/bin/
     - /Users/mchabot/bin
     - /usr/local/mongodb/bin
     - /Users/mchabot/bin/shared
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/local/mysql/bini
     - /opt/local/lib/postgresql84/bin
     - /Users/mchabot/bin/FDK/Tools/osx
     - /Users/mchabot/bin/FDK/Tools/osx 
```

Do you have an idea what might be the issue?

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 8 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/boson#53). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by martinos** [comment]
I think that this is an issue for the boson-more gem.  It seems that there is a missing dependency on the alias gem in the boson-more.gemspec.

**Comment by zhando** [comment]
I filed an issue on this problem and came to a conclusion:

https://github.com/cldwalker/boson-more/issues/1

i.e. because all of the plugins in boson-more are considered "optional" and their dependencies are documented - it shouldn't be required to put alias and hirb in the .gemspec..

gem install alias hirb

should do the trick for the most common use case.

**Comment by cldwalker** [comment]
@zhando explained it pretty well - boson-more is a collection of plugins and I didn't want to force the dependencies. [This explains the dependencies in more detail](https://github.com/cldwalker/boson-more#list-of-plugins). If the docs are confusing in boson-more, feel free to give me a pull or explain what could be improved.
